config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'products#index'
  resources :likes, only: [:create, :destroy]
  resources :pages, only: [:index, :new]
  resources :cards, only: [:index, :new, :create, :destroy]
  resources :categories, only: [:show]
  resources :brands, only: [:show]

  resources :products do
    member do
      get 'product_show'
      get 'buy'
      post 'pay'
    end
    collection do
      get 'header_category', defaults: { format: 'json' }
      get 'products/children_category', defaults: { format: 'json' }
      get 'products/grandchild_category', defaults: { format: 'json' }
      get 'products/product_size_brand', defaults: { format: 'json' }
      get 'products/brand_search', defaults: { format: 'json' }
    end
  end
  resources :users, only: [:index,:edit,:show,:new] do
    member do
      get 'exhibit_list'
      get 'identification'
      get 'logout'
    end
    collection do
      get 'card'
      get 'signup/step1'
      get 'signup/step2'
      get 'signup/step3'
      get 'signup/step4'
      get 'signup/complete'
      get 'children_category', defaults: { format: 'json' }
      get 'grandchild_category', defaults: { format: 'json' }
      get 'product_size_brand', defaults: { format: 'json' }
      get 'brand_search', defaults: { format: 'json' }      
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  
  has_many :cards
  has_many :sns_credentials
  has_many :products

  VALID_EMAIL_REGEX =                 /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX =              /\A(?=.*?[a-z])(?=.*?\d)(?=.*?\W)[!-~]+\z/i
  VALID_PHONE_REGEX =                 /\A\d{10,11}\z/
  VALID_KANA_REGEX =                  /\A[ァ-ヶー－]+\z/
  VALID_POST_REGEX =                  /\A\d{7}\z/

  #ユーザー登録
  #form1のバリデーション
  validates :nickname,                presence: true, length: {maximum: 20}, on: :validates_step1
  validates :email,                   format: { with: VALID_EMAIL_REGEX }, on: :validates_step1
  validates :last_name,               presence: true, length: {maximum: 35}, on: :validates_step1
  validates :name,                    presence: true, length: {maximum: 35}, on: :validates_step1
  validates :last_name_f,             presence: true, format: { with: VALID_KANA_REGEX }, length: {maximum: 35}, on: :validates_step1
  validates :name_f,                  presence: true, format: { with: VALID_KANA_REGEX }, length: {maximum: 35}, on: :validates_step1
  validates :birthday,                presence: true, on: :validates_step1
  
  #form2のバリデーション
  validates :phone_number,            presence: true, uniqueness: true, format: { with: VALID_PHONE_REGEX }, on: :validates_step2

  #form3のバリデーション
  validates :d_last_name,             presence: true, length: {maximum: 35}, on: :validates_step3
  validates :d_name,                  presence: true, length: {maximum: 35}, on: :validates_step3
  validates :d_last_name_f,           presence: true, format: { with: VALID_KANA_REGEX }, length: {maximum: 35}, on: :validates_step3
  validates :d_name_f,                presence: true, format: { with: VALID_KANA_REGEX }, length: {maximum: 35}, on: :validates_step3
  validates :postal_code,             presence: true, format: { with: VALID_POST_REGEX }, on: :validates_step3
  validates :prefecture,              presence: true, on: :validates_step3
  validates :city,                    presence: true, length: {maximum: 35}, on: :validates_step3
  validates :address,                 presence: true, length: {maximum: 125}, on: :validates_step3
  validates :building_name,           length: {maximum: 125}, on: :validates_step3
  validates :d_phone_number,          length: {maximum: 20}, on: :validates_step3

  def self.without_sns_data(auth)
    user = User.find_by(email: auth.info.email)

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email,
          password: Devise.friendly_token.first(7)
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
    end

   def self.with_sns_data(auth, snscredential)
    user = User.find(snscredential.user_id)
    if user.nil?
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
        password: Devise.friendly_token.first(7)
      )
    end
    return {user: user}
   end

   def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      session[:provider] = @sns[:provider]
      session[:uid] = @sns[:uid]
      render template: "signup/step1"
    end
  end

  def failure
    redirect_to root_path 
  end
  
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_category
  
  def index
  end
  
  def show
    @user = User.find(params[:id]) 
  end

  def card
  end

  def logout
  end

  def exhibit_list
    @products = Product.where(user_id: current_user.id)
  end

  def identification
    @user = User.find(params[:id])
  end

  
  private

  def set_category
    @parents = Category.all.order("id ASC").limit(13)
  end

  def user_params
    params.require(:user).permit(:nickname,:v_good,:v_accept,:v_bad)
  end

  def new
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/card.html.haml
%html#mypage-all
  %body#mypage-show
    %nav.bread-crumbs
      %ul.bread-crumbs-list
        - breadcrumb :pay
        = breadcrumbs separator: " &rsaquo; ", class: 'bread-top'
    .main-user
      .l-content
        .mypage__user--card--header
          %h2.mypage__user--card--header--title
            支払い方法
        .mypage__user--card--content
          %section.mypage__user--card--content-section
            .mypage__user--card--content--title
              クレジットカード一覧
            %ul.setting-card-content
              %li
                %form{class:'setting-card-content-list', action: '#', method: 'post'}
                  %figure
                    = image_tag 'jcb-emblem-logo.svg', alt: 'JCB', height: '50px', width: '50px', class: 'setting-card-logo'
                  .setting-card-logo-num
                    %p
                      *****************5141
                    %p 
                      11/21
                  %button{onclick: "location.href='#'", class: 'setting-card-content-button'}
                    削除する
          .mypage__user--card--content-under-text
            = link_to "#", class: "mypage__user--card--content-under-text-link" do
              .mypage__user--card--content-under-text-link-text
                %small.user-card-small-text 支払い方法について
                %i.fas.fa-chevron-right
      = render 'shared/user-mypage-lsidebar'
    

app/views/users/exhibit_list.html.haml
= render partial: 'products/header_index', locals: {parents:  @parents}
%html#mypage-all
  %body#mypage-show
    %nav.bread-crumbs
      %ul.bread-crumbs-list
        - breadcrumb :users
        = breadcrumbs separator: " &rsaquo; ", class: 'bread-top'
    .main-user-form.clearfix
      .main-user-form__exhibit
        .main-user-form__exhibit--title
          出品した商品
        - if @products.length > 0
          - @products.each do |product|
            = link_to product_show_product_path(id: product.id), class:"main-user-form__exhibit--list",data: {"turbolinks" => false} do
              .main-user-form__exhibit--list--image
                = image_tag "#{product.images[0].picture.url}", class:"picture"
              .main-user-form__exhibit--list--info
                .main-user-form__exhibit--list--info--title
                  = product.name
                .main-user-form__exhibit--list--info--status
                  出品中
              %i.fas.fa-chevron-right.main-user-form__exhibit--list--icon
        - else
          .main-user-form__exhibit--list
            .main-user-form__exhibit--list--info--title
              現在出品中の商品はありません
      = render 'shared/user-mypage-lsidebar'
= render 'shared/exhibit-icon'
= render 'shared/footer'

app/views/users/identification.html.haml
= render partial: 'products/header_index', locals: {parents:  @parents}
%html#mypage-all
  %body#mypage-show
    %nav.bread-crumbs
      %ul.bread-crumbs-list
        - breadcrumb :users
        = breadcrumbs separator: " &rsaquo; ", class: 'bread-top'
    .main-identification.clearfix
      .main-identification__content
        %h2.main-identification__content--title 本人情報の登録
        .main-identification__content__form
          %p
            お客さまの本人情報をご登録ください。
            %br
            登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
          %p.text-right
            = link_to "本人確認書類のアップロードについて>", "https://www.mercari.com/jp/help_center/article/495/", class:"text-right--info"
          .main-identification__content__form--group
            .main-identification__content__form--group--label お名前
            = @user.last_name
            = @user.name
          .main-identification__content__form--group
            .main-identification__content__form--group--label お名前カナ
            = @user.d_last_name_f
            = @user.d_name_f
          .main-identification__content__form--group
            .main-identification__content__form--group--label 生年月日
            = @user.birthday
          .main-identification__content__form--group
            %label.main-identification__content__form--group--label 郵便番号
            %span.any 任意
          %input.select-box--menu.choosing{placeholder: "例）1234567", type: "text", value: "#{@user.postal_code}"}
          .main-identification__content__form--group
            %label.main-identification__content__form--group--label 都道府県
            %span.any 任意
          .select-box
            %i.icon-deco.fa.fa-angle-down.fa-2x
            %select.select-box--menu.choosing{value: "#{@user.prefecture}"}
              - Prefecture.all.each do |f|
                %option{value:"f.name"} #{f[:name]}
          .main-identification__content__form--group
            %label.main-identification__content__form--group--label 市区町村
            %span.any 任意
          %input.select-box--menu.choosing{placeholder: "例) 横浜市緑区", type: "text", value: "#{@user.city}"}
          .main-identification__content__form--group
            %label.main-identification__content__form--group--label 番地
            %span.any 任意
          %input.select-box--menu.choosing{placeholder: "例) 青山1−1−1", type: "text", value: "#{@user.address}"}
          .main-identification__content__form--group
            %label.main-identification__content__form--group--label 建物名
            %span.any 任意
          %input.select-box--menu.choosing{placeholder: "例) 柳ビル103", type: "text", value: "#{@user.building_name}"}
          %button.btn-submit.choosing{type: "submit"} 登録する
          .main-identification__content__form--group.text-right
            = link_to "本人情報の登録について>", "https://www.mercari.com/jp/help_center/article/423/", class:"main-identification__content__form--group--info"
      = render 'shared/user-mypage-lsidebar'
= render 'shared/exhibit-icon'
= render 'shared/footer'

app/views/users/index.html.haml
= render partial: 'products/header_index', locals: {parents:  @parents}
%html#mypage-all
  %body#mypage-show
    %nav.bread-crumbs
      %ul.bread-crumbs-list
        - breadcrumb :users
        = breadcrumbs separator: " &rsaquo; ", class: 'bread-top'
  .main-user-body
    .main-user.clearfix
      .l-content
        .mypage__user--icon
          = link_to "#", class: "mypage__user--icon--content" do
            .figure
              = image_tag '8e315ba2cbcce728cf0bf8f71f2e5818.png', class:"figure--avater"
              %h2.figure--name #{current_user.nickname}
              .mypage__number
                = "評価 0 出品数 #{current_user.products.length}"
        .mypage__tab--container
          %ul.mypage-tabs
            .box
              %li.active-left
                .active-text-left
                  お知らせ
            %li.active-right
              .active-text-right
                やることリスト
            .active
              .box-after
                %li.active-left-after
                  .active-text-left-after
                    お知らせ
              %li.active-right-after
                .active-text-right-after
                  やることリスト
          .tab-content
            %ul.mypage__item-list
              %li 
                = link_to "#", class: "mypage-item-link" do
                  .figure 
                    = image_tag '95750e8a4355cdb0592222e962c61f99.png', height: '48px', width: '48px'
                  .mypage__item--body
                    .mypage__item--text
                      事務局から個別メッセージ
                    %time
                      %i.far.fa-clock
                      5時間前
                    %i.fas.fa-chevron-right
              %li 
                = link_to "#", class: "mypage-item-link" do
                  .figure 
                    = image_tag '95750e8a4355cdb0592222e962c61f99.png', height: '48px', width: '48px'
                  .mypage__item--body
                    .mypage__item--text
                      事務局から個別メッセージ
                    %time
                      %i.far.fa-clock
                      ５時間前
                    %i.far.fa-heart
              %li 
                = link_to "#", class: "mypage-item-link" do
                  .figure 
                    = image_tag '95750e8a4355cdb0592222e962c61f99.png', height: '48px', width: '48px'
                  .mypage__item--body
                    .mypage__item--text
                      事務局から個別メッセージ
                    %time
                      %i.far.fa-clock
                      ５時間前
                    %i.fas.fa-chevron-right
              %li 
                = link_to "#", class: "mypage-item-link" do
                  .figure 
                    = image_tag '95750e8a4355cdb0592222e962c61f99.png', height: '48px', width: '48px'
                  .mypage__item--body
                    .mypage__item--text
                      事務局から個別メッセージ
                    %time
                      %i.far.fa-clock
                      ５時間前
                    %i.fas.fa-chevron-right
              %li.mypage-item-link-list
                = link_to "#" do
                  一覧を見る
          .tab-content-after
            %ul
              %li.tab-content-after-content
                
          .tab-content-under
            %h2.mypage-tab-head 
              購入した商品
            %ul.mypage-tabs-under
              .box-under
                %li.active-left-under
                  %h3
                    .active-text-left-under
                      取引中
              %li.active-right-under
                %h3
                  .active-text-right-under
                    過去の取引
              .active-under
                .box-after
                  %li.active-left-after
                    .active-text-left-after
                      取引中
                %li.active-right-after
                  .active-text-right-after
                    過去の取引
      = render 'shared/user-mypage-lsidebar'
= render 'shared/exhibit-icon'
= render 'shared/footer'
:javascript
  $('.active-text-right').on('click',function(){
  $('.tab-content').hide();
  $('.box').hide();
  $('.active-right').hide();
  $('.active').show();
  $('.tab-content-after').show();
  });
  $('.active-text-left-after').on('click',function(){
  $('.active').hide();
  $('.tab-content-after').hide();
  $('.tab-content').show();
  $('.box').show();
  $('.active-right').show();
  });
  $('.active-text-right-under').on('click',function(){
  $('.box-under').hide();
  $('.active-right-under').hide();
  $('.active-under').show();
  });
  $('.active-text-left-after').on('click',function(){
  $('.active-under').hide();
  $('.box-under').show();
  $('.active-right-under').show();
  });

app/views/users/logout.html.haml
= render partial: 'products/header_index', locals: {parents:  @parents}
%html#mypage-all
  %body#mypage-show
    %nav.bread-crumbs
      %ul.bread-crumbs-list
        - breadcrumb :users
        = breadcrumbs separator: " &rsaquo; ", class: 'bread-top'
    .main-user-form.clearfix
      .main-user-form__box
        .main-user-form__box--btn
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-logout'
      = render 'shared/user-mypage-lsidebar'
= render 'shared/exhibit-icon'
= render 'shared/footer'