config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'products#index'
  resources :likes, only: [:create, :destroy]
  resources :pages, only: [:index, :new]
  resources :cards, only: [:index, :new, :create, :destroy]
  resources :categories, only: [:show]
  resources :brands, only: [:show]

  resources :products do
    member do
      get 'product_show'
      get 'buy'
      post 'pay'
    end
    collection do
      get 'header_category', defaults: { format: 'json' }
      get 'products/children_category', defaults: { format: 'json' }
      get 'products/grandchild_category', defaults: { format: 'json' }
      get 'products/product_size_brand', defaults: { format: 'json' }
      get 'products/brand_search', defaults: { format: 'json' }
    end
  end
  resources :users, only: [:index,:edit,:show,:new] do
    member do
      get 'exhibit_list'
      get 'identification'
      get 'logout'
    end
    collection do
      get 'card'
      get 'signup/step1'
      get 'signup/step2'
      get 'signup/step3'
      get 'signup/step4'
      get 'signup/complete'
      get 'children_category', defaults: { format: 'json' }
      get 'grandchild_category', defaults: { format: 'json' }
      get 'product_size_brand', defaults: { format: 'json' }
      get 'brand_search', defaults: { format: 'json' }      
    end
  end
end

app/views/shared/_categories.html.haml
%h2#header-nav__parent__root
  = link_to root_path,class:"h-deco" do
    %i.fa.fa-list-ul.h-link-icon.fa-lg
    %span.h-link カテゴリから探す
  %ul.header-nav__parent
    %li.header-nav__parent__detail
      =link_to "レディース","#",class:'a'
      %ul.header-nav__child
        %li.header-nav__child__detail
          =link_to "トップス","#",class:'a'
          %ul.header-nav__grand-child
            %li.header-nav__grand-child__detail
              =link_to "Tシャツカットソー(半袖袖なし)","#",class:'a'
            %li.header-nav__grand-child__detail
              =link_to "Tシャツカットソー(七分長袖)","#",class:'a'
        %li.header-nav__child__detail
          =link_to "ジャケット・アウター","#",class:'a'
          %ul.header-nav__grand-child
            %li.header-nav__grand-child__detail
              =link_to "テーラードジャケット","#",class:'a'
            %li.header-nav__grand-child__detail
              =link_to "ノーカラージャケット","#",class:'a'
    %li.header-nav__parent__detail
      =link_to "メンズ","#",class:'a'
    %li.header-nav__parent__detail
      =link_to "ベビー・キッズ","#",class:'a'

app/views/shared/_categories_product_block.html.haml
%li.product__block__li
  = link_to "/products/#{product.id}", class: "product__block__li__link" do
    .product__block__li__link__image
      - product.images.first(1).each do |image|
        = image_tag image.picture.to_s, size: "188x188", alt: "picture", class: "product__block__li__link__image__picture"
      .product__block__li__link__price
        = "¥#{product.price.to_s(:delimited, delimiter: ',')}"
    .product__block__li__link__title
      .product__block__li__link__title__name
        = product.name
      .product__block__li__link__title__num
        .product__block__li__link__title__num__font
          %i.far.fa-heart.product__block__li__link__title__num__font__heart-mark
          %span.product__block__li__link__title__num__font__lank 

app/views/shared/_exhibit-icon.html.haml
.exhibit-icon
  = link_to "出品", new_product_path, class: "exhibit-icon--text",data: {"turbolinks" => false}
  %i.fas.fa-camera.fa-4x.exhibit-icon--icon

app/views/shared/_footer.html.haml
.f-container
  .app-banner
  .global-footer
    .global-footer__cell-1
      %h2.global-footer__cell-1__title
        メルカリについて
        %li
          = link_to "会社概要（運営会社)",root_path, class: 'a'
        %li
          = link_to "採用情報",root_path,class: 'a'
        %li
          = link_to "プレスリリース",root_path,class: 'a'
        %li
          = link_to "公式ブログ",root_path,class: 'a'
        %li
          = link_to "メルカリロゴ利用ガイドライン",class: 'a'
        %li.social-link-f1
          = link_to "#" do
            %i.fab.fa-twitter.icon_f.fa-3x
        %li.social-link-f2
          = link_to "#",class:"a" do
            %i.fab.fa-facebook-square.icon_f.fa-3x

    .global-footer__cell-2
      %h2.global-footer__cell-2__title
        ヘルプ＆ガイド
        %li
          = link_to "メルカリガイド",root_path,class: 'a'
        %li
          = link_to "らくらくメルカリ便",root_path,class: 'a'
        %li
          = link_to "ゆうゆうメルカリ便",root_path,class: 'a'
        %li
          = link_to "大型メルカリ便",root_path,class: 'a'
        %li
          = link_to "車体取引ガイド",root_path,class: 'a'
        %li
          = link_to "メルカリあんしん・あんぜん宣言！",root_path,class: 'a'
        %li
          = link_to "偽ブランド品撲滅への取り組み",root_path,class: 'a'
        %li
          = link_to "メルカリボックス",root_path,class: 'a'

    .global-footer__cell-3
      %h2.global-footer__cell-3__title
        プライバシーと利用規約
      .global-footer__cell-3__inner-left
        %li
          = link_to "プライバシーポリシー",root_path,class: 'a'
        %li
          = link_to "メルカリ利用規約",root_path,class: 'a'
        %p.f
          = link_to "あんしんスマホサポート制度に関する",root_path,class: 'a'
        %p.f  
          = link_to "利用特約",root_path,class: 'a'
        %li
          = link_to "コンプライアンスポリシー",root_path,class: 'a'
      .global-footer__cell-3__inner-right
        %p.f
          = link_to "個人データの安全管理に係る",root_path,class: 'a'
        %p.f  
          = link_to "基本方針",root_path,class: 'a'
        %li
          = link_to "特定商取引に関する表記",root_path,class: 'a'
        %li
          = link_to "資金決済法に基づく表示",root_path,class: 'a'
        %li
          = link_to "法令順守と犯罪抑止のために",root_path,class: 'a'
    .global-footer__language
      %h2.global-footer__language__title
        国
        %li
          = link_to "日本",root_path,class: 'a'
        %li
          = link_to "United States",root_path,class: 'a'
  .footer-bottom
    .footer-bottom__mercari-f-icon
      = link_to "", root_path, class:'mercari-footer-i'
    .footer-bottom__copyright-i

app/views/shared/_product_block.html.haml
%li.product__block__li
  = link_to "/products/#{product.id}", class: "product__block__li__link" do
    .product__block__li__link__image
      - product.images.first(1).each do |image|
        = image_tag image.picture.to_s, size: "188x188", alt: "picture", class: "product__block__li__link__image__picture"
      .product__block__li__link__price
        = "¥#{product.price.to_s(:delimited, delimiter: ',')}"
    .product__block__li__link__title
      .product__block__li__link__title__name
        = product.name

app/views/shared/_user-mypage-lsidebar.html.haml
.l-side
  %nav.mypage__nav
    %ul.mypage__nav--list
      %li.mypage__nav--list--index
        = link_to "マイページ", users_path, class: "mypage__nav--list--index--menu" 
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "お知らせ", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "やることリスト", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "いいね！一覧", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "出品する", new_product_path, class: "mypage__nav--list--index--menu",data: {"turbolinks" => false}
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "出品した商品 - 出品中", exhibit_list_user_path(id: current_user.id), class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "出品した商品 - 取引中", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "出品した商品 - 売却済み", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "購入した商品 - 取引中", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "購入した商品 - 取引中", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "購入した商品 - 過去の取引", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "ニュース一覧", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "評価一覧", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "ガイド", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "お問い合わせ", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
    %h3.mypage__nav--title
      メルペイ
    %ul.mypage__nav--list
      %li.mypage__nav--list--index
        = link_to "売上・振込申請", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "ポイント", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
    %h3.mypage__nav--title
      設定
    %ul.mypage__nav--list
      %li.mypage__nav--list--index
        = link_to "プロフィール", pages_path, class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "発送元・お届け先住所変更", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "支払い方法", cards_path, class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "メール/パスワード", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "本人情報", identification_user_path(id: current_user.id), class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "電話番号の確認", "#", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon
      %li.mypage__nav--list--index
        = link_to "ログアウト", "/users/#{current_user.id}/logout", class: "mypage__nav--list--index--menu"
        %i.fas.fa-chevron-right.mypage__nav--list--index--icon

app/views/shared/_user_information.html.haml
.products__content--buy--address
  .products__content--buy--address--inner
    %p.products__content--buy--address--inner--title
      配送先
    %address.products__content--buy--address--inner--address
      %p
        = "〒#{current_user.postal_code.to_s[0..2]}-#{current_user.postal_code.to_s[3..6]}"
      %p 
        = "#{current_user.prefecture} #{current_user.city} #{current_user.address}"
      %p 
        = "#{current_user.last_name} #{current_user.name}"
    = link_to '#', class: 'products__content--buy--address--inner--address--link' do
      .products__content--buy--address--inner--address--link--text
        %small.address--link--small--text 変更する
        %i.fas.fa-chevron-right
.products__content--buy--address
  .products__content--buy--address--inner
    %p.products__content--buy--address--inner--title
      支払い方法
    - if @card_information.present?
      %address.products__content--buy--address--inner--address
        %p 
          = "*****************" + @card_information.last4
        %p  
          - exp_month = @card_information.exp_month.to_s
          - exp_year = @card_information.exp_year.to_s.slice(2,2)
          = exp_month + "/" + exp_year
        = render 'cards/card_logo'
      = link_to '/cards', class: 'products__content--buy--address--inner--address--link' do
        .products__content--buy--address--inner--address--link--text
          %small.address--link--small--text 変更する
          %i.fas.fa-chevron-right
    - else
      %address.products__content--buy--address--inner--address
        %br /
      = link_to '/cards/new', class: 'products__content--buy--address--inner--address--link' do
        .products__content--buy--address--inner--address--link--text
          %small.address--link--small--text 変更する
          %i.fas.fa-chevron-right