config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'products#index'
  resources :likes, only: [:create, :destroy]
  resources :pages, only: [:index, :new]
  resources :cards, only: [:index, :new, :create, :destroy]
  resources :categories, only: [:show]
  resources :brands, only: [:show]

  resources :products do
    member do
      get 'product_show'
      get 'buy'
      post 'pay'
    end
    collection do
      get 'header_category', defaults: { format: 'json' }
      get 'products/children_category', defaults: { format: 'json' }
      get 'products/grandchild_category', defaults: { format: 'json' }
      get 'products/product_size_brand', defaults: { format: 'json' }
      get 'products/brand_search', defaults: { format: 'json' }
    end
  end
  resources :users, only: [:index,:edit,:show,:new] do
    member do
      get 'exhibit_list'
      get 'identification'
      get 'logout'
    end
    collection do
      get 'card'
      get 'signup/step1'
      get 'signup/step2'
      get 'signup/step3'
      get 'signup/step4'
      get 'signup/complete'
      get 'children_category', defaults: { format: 'json' }
      get 'grandchild_category', defaults: { format: 'json' }
      get 'product_size_brand', defaults: { format: 'json' }
      get 'brand_search', defaults: { format: 'json' }      
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :authenticate_user!
  before_action :set_category, only: [:index]
  before_action :set_card


  def index   # カード確認画面
    @parents = Category.all.order("id ASC").limit(13)
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"] 
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)

      @card_brand = @card_information.brand
      case @card_brand
      when "Visa"
        @card_logo = "visa.svg"
      when "JCB"
        @card_logo = "jcb.svg"
      when "MasterCard"
        @card_logo = "mastercard.svg"
      when "American Express"
        @card_logo = "american-express.svg"
      when "Diners Club"
        @card_logo = "diners-club-international.svg"
      when "Discover"
        @card_logo = "discover.svg"
      end 
    else
      redirect_to action: "new" 
    end
  end

  def destroy   # カード情報削除
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"] 
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete
    @card.delete
    redirect_to action: "new"
  end
  
  def new   # カード登録画面
    redirect_to action: "index" if @card.present?
  end

  def create  # カード登録処理
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        description: 'test', 
        email: current_user.email,
        card: params['payjp-token'], 
        metadata: {user_id: current_user.id} 
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "create"
      end     
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end

  def set_category
    @parents = Category.all.order("id ASC").limit(13)
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card_logo.html.haml
%figure
  = image_tag "#{@card_logo}", alt: @card_brand, height: '50px', width: '50px', class: 'setting-card-logo'

app/views/cards/index.html.haml
= render partial: 'products/header_index', locals: {parents:  @parents}
%html#mypage-all
  %body#mypage-show
    %nav.bread-crumbs
      %ul.bread-crumbs-list
        - breadcrumb :pay
        = breadcrumbs separator: " &rsaquo; ", class: 'bread-top'
    .main-user.clearfix
      .l-content
        .mypage__user--card--header
          %h2.mypage__user--card--header--title
            支払い方法
        .mypage__user--card--content
          %section.mypage__user--card--content-section
            .mypage__user--card--content--title
              クレジットカード一覧
            %ul.setting-card-content
              %li.setting-card-content-list
                = form_with url: card_path(@card.id), method: :delete, local: true, id: 'card-form' do |f|
                  = render 'card_logo'
                  .setting-card-logo-num
                    = "*****************" + @card_information.last4
                  .setting-card-logo-num
                    - exp_month = @card_information.exp_month.to_s
                    - exp_year = @card_information.exp_year.to_s.slice(2,2)
                    = exp_month + "/" + exp_year
                  %button{onclick: "location.href='./_register.html'", class: 'setting-card-content-button'}
                    削除する
          .mypage__user--card--content-under-text
            = link_to "#", class: "mypage__user--card--content-under-text-link" do
              .mypage__user--card--content-under-text-link-text
                %small.user-card-small-text 支払い方法について
                %i.fas.fa-chevron-right
      = render 'shared/user-mypage-lsidebar'
= render 'shared/exhibit-icon'
= render 'shared/footer'

app/views/cards/new.html.haml
.signup-form
  .signup-form__container
    %h2.signup-form__container__title
      クレジットカード情報入力
    .signup-form__container__main
      = form_tag("/cards", method: :post, id: 'charge-form',  name: "inputForm", class: 'signup-form__container__inner') do
        .signup-form__container__inner__form
          .signup-form__container__inner__form__pack-label
            %span.signup-form__container__inner__form__pack-label__text 
              カード番号
            %span.signup-form__container__inner__form__pack-label__required-i 
              必須
          %label
          = text_field_tag "card_number", "", class: "signup-form__container__inner__form__field", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          .form4__container__inner__form__image
            .form4__container__inner__form__image__ul
              = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?465897195', class: "form4__container__inner__form__image__ul__li"
              = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?465897195', class: "form4__container__inner__form__image__ul__li"
              = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?465897195', class: "form4__container__inner__form__image__ul__li"
              = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?465897195', class: "form4__container__inner__form__image__ul__li"
              = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?465897195', class: "form4__container__inner__form__image__ul__li"
              = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?465897195', class: "form4__container__inner__form__image__ul__li"
              = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?465897195', class: "form4__container__inner__form__image__ul__li"
        .signup-form__container__inner__form
          .signup-form__container__inner__form__pack-label
            %span.signup-form__container__inner__form__pack-label__text 
              有効期限
            %span.signup-form__container__inner__form__pack-label__required-i 
              必須
          = render "signup/credit_expiration"
        .signup-form__container__inner__form
          .signup-form__container__inner__form__pack-label
            %span.signup-form__container__inner__form__pack-label__text 
              セキュリティーコード
            %span.signup-form__container__inner__form__pack-label__required-i 
              必須
          %label
          = text_field_tag "cvc", "", class: "cvc signup-form__container__inner__form__field", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
          %img_tag.signup-form__container__inner__form__image
        .signup-form__container__inner__question
          カードの裏面の番号とは？
        #card_token
        = submit_tag "追加する", id: "token_submit", class: 'signup-form__container__inner__submit'
= render 'signup/form-footer'