config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'products#index'
  resources :likes, only: [:create, :destroy]
  resources :pages, only: [:index, :new]
  resources :cards, only: [:index, :new, :create, :destroy]
  resources :categories, only: [:show]
  resources :brands, only: [:show]

  resources :products do
    member do
      get 'product_show'
      get 'buy'
      post 'pay'
    end
    collection do
      get 'header_category', defaults: { format: 'json' }
      get 'products/children_category', defaults: { format: 'json' }
      get 'products/grandchild_category', defaults: { format: 'json' }
      get 'products/product_size_brand', defaults: { format: 'json' }
      get 'products/brand_search', defaults: { format: 'json' }
    end
  end
  resources :users, only: [:index,:edit,:show,:new] do
    member do
      get 'exhibit_list'
      get 'identification'
      get 'logout'
    end
    collection do
      get 'card'
      get 'signup/step1'
      get 'signup/step2'
      get 'signup/step3'
      get 'signup/step4'
      get 'signup/complete'
      get 'children_category', defaults: { format: 'json' }
      get 'grandchild_category', defaults: { format: 'json' }
      get 'product_size_brand', defaults: { format: 'json' }
      get 'brand_search', defaults: { format: 'json' }      
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :images, dependent: :destroy
  belongs_to :user
  belongs_to :brand, optional: true
  belongs_to :category
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, :introduction, :status, :d_charge, :d_method, :d_origin, :d_interval, :category_id, :price,  presence: true
end

  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'payjp'
  before_action :authenticate_user!, only: [:new, :buy]
  before_action :set_card, only: [:buy, :pay]
  before_action :set_product, only: [:show, :buy, :pay, :product_show, :destroy, :edit, :update]
  before_action :set_category, only: [:index, :show, :product_show, :destroy]
  

  def index
    @categories = Category.find(1,2,8,6)
    @ladies_products = []
    @categories[0].children.each do |child_category|
      child_category.children.each do |grandchild_category|
        @ladies_products += grandchild_category.products
      end
    end
    @ladies_products.sort_by!{|ladies_product|ladies_product.created_at}.reverse!

    @mens_products = []
    @categories[1].children.each do |child_category|
      child_category.children.each do |grandchild_category|
        @mens_products += grandchild_category.products
      end
    end
    @mens_products.sort_by!{|mens_product|mens_product.created_at}.reverse!

    @electric_products = []
    @categories[2].children.each do |child_category|
      child_category.children.each do |grandchild_category|
        @electric_products += grandchild_category.products
      end
    end
    @electric_products.sort_by!{|electric_product|electric_product.created_at}.reverse!

    @hobby_products = []
    @categories[3].children.each do |child_category|
      child_category.children.each do |grandchild_category|
        @hobby_products += grandchild_category.products
      end
    end
    @hobby_products.sort_by!{|hobby_product|hobby_product.created_at}.reverse!

    @chanel_products = Product.where(brand_id: 125).order("created_at DESC")
    @ruiviton_products = Product.where(brand_id: 126).order("created_at DESC")
    @shupurimu_products = Product.where(brand_id: 127).order("created_at DESC")
    @naiki_products = Product.where(brand_id: 128).order("created_at DESC")
  end

  def new
    @product = Product.new
    @product.images.build
  end

  def edit
    @g_category = Category.find(@product.category_id)
    @c_category = @g_category.parent
    @p_category = @c_category.parent
    @Categories = @p_category.children
    @clothe_default_size = @product.product_size
    if @product.brand_id != nil
      @brand_id = @product.brand_id
      @brand = Brand.find(@product.brand_id)
    end
    @all_brands = Brand.all
  end

  def update
    if @product.update(edit_product)
      redirect_to product_show_product_path, notice: "変更しました。"
    else
      render :edit
    end
  end
  
  def show
    @product = Product.find(params[:id])
    @user = @product.user
    @other_products = @user.products.where.not(id: @product.id)
    @ordered_other_products = @other_products.order('id DESC').limit(6)
    @parent_category_id = @product.category.ancestry[/.*\//, 0].sub(/\//,"")
    @parent_category_name = Category.find(@parent_category_id).name
    @child_category_id = @product.category.ancestry[/\/.*/, 0].sub(/\//,"")
    @child_category_name = Category.find(@child_category_id).name
    @same_category_products = Product.where(category_id: "#{@product.category_id}").where.not(id: @product.id).order('id DESC').limit(6)
    @reverse_ordered_products = Product.order('id DESC')
    if Product.where('id <?',@product.id).present?
      @previous_product = @reverse_ordered_products.where('id < ?',@product.id).first
    else
      @previous_product = Product.order('id DESC').first
    end  
    if Product.where('id >?',@product.id).present?
      @next_product = Product.where('id >?',@product.id).first
    else
      @next_product = Product.order('id ASC').first
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path, notice: "出品が完了しました"
    else
      render :new 
    end
  end

  def destroy
    if @product.destroy
      redirect_to exhibit_list_user_path(id: current_user.id), notice: "削除しました"
    else
      render :product_show
    end
  end

  def product_show
    @images = @product.images
    @category = @product.category
  end

  def header_category
    @category_id = Category.find("#{params[:category_id]}").children
  end

  def children_category
    @children_category = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def grandchild_category
    @grandchild_category = Category.find("#{params[:child_id]}").children
  end

  def product_size_brand 
    @product_name = Category.find_by(name: "#{params[:category_name]}")
    @grand_category_clothes = Grand_category.all
    @grand_category_shoes = Shoes_category.all
    @clothes = @grand_category_clothes.map { |c| c[:name] }
    @shoes = @grand_category_shoes.map { |s| s[:name] }
    if @clothes.include?(@product_name[:name])
      @size_form = 2
    elsif @shoes.include?(@product_name[:name])
      @size_form = 1
    else
      @size_form = 0
    end
  end

  def brand_search
    @brand_name = Brand.where('name LIKE ?', "%#{params[:keyword]}%")
    @brand_key1 = Brand.where('keyword1 LIKE ?', "%#{params[:keyword]}%")
    @brand_key2 = Brand.where('keyword2 LIKE ?', "%#{params[:keyword]}%")
    if @brand_name != []
      @brands = @brand_name
    elsif @brand_key1 != []
      @brands = @brand_key1
    else
      @brands = @brand_key2
    end
  end
  
  def buy # 購入確認
    set_card_information
  end

  def pay # 決済処理
    set_card_information
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"] 
    Payjp::Charge.create(
      amount: @product.price, 
      customer: @card.customer_id,
      currency: 'jpy',
    )
  end

  private

  def set_category
    @parents = Category.all.order("id ASC").limit(13)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
      :name, 
      :introduction,
      :status,
      :d_charge,
      :d_method,
      :d_origin,
      :d_interval,
      :price,
      :product_size,
      :category_id,
      :brand_id,
      images_attributes:[:picture]
      ).merge(user_id: current_user.id)
  end

  def edit_product
    params.require(:product).permit(
      :name, 
      :introduction,
      :status,
      :d_charge,
      :d_method,
      :d_origin,
      :d_interval,
      :price,
      :product_size,
      :category_id,
      :brand_id
      ).merge(user_id: current_user.id)
  end


  def set_card
    @card = current_user.cards.first if current_user.cards.present?
  end  

  def set_card_information
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"] 
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)

      @card_brand = @card_information.brand
      case @card_brand
      when "Visa"
        @card_logo = "visa.svg"
      when "JCB"
        @card_logo = "jcb.svg"
      when "MasterCard"
        @card_logo = "mastercard.svg"
      when "American Express"
        @card_logo = "american-express.svg"
      when "Diners Club"
        @card_logo = "diners-club-international.svg"
      when "Discover"
        @card_logo = "discover.svg"
      end  
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_exhibit-header.html.haml
.exhibit-header
  = link_to image_tag("mercari-header-logo.png", alt: "mercari", class: "eh-logo"), root_path

app/views/products/_header_index.html.haml
.header
  .header-inner
    .header-inner__top
      .header-inner__top__logo
        = link_to root_path, alt: "メルカリアイコン",class:'mercari-icon' do
          = image_tag "mercari_toppage_logo.svg",size: "135x36"
      .header-inner__top__form
        %form{action: "https://www.mercari.com/jp/search/"}
          %input.form_search{placeholder: "何かお探しですか？"}
            %label.header-inner__top__form__search-icon_r
              = fa_icon 'search fa-lg',class:'submit'
    .header-inner__bottom
      .header-inner__bottom__search
        .header-inner__bottom__search--categories
          .category
            = image_tag 'https://i.gyazo.com/a8ab7bb03ef6cd322006bffe7eb04005.png',class: ''
            カテゴリーから探す
          %ul#parents
            - parents.each do |parent|
              %li.parent
                = link_to "#{parent.name}", category_path(parent.id), class:"parent--text", data: {"category-id" => "#{parent.id}"}
            %li.parent
              = link_to "カテゴリ一覧", "#", class: "parent--text"
            %ul#children
              %ul#grand_children
        .header-inner__bottom__search--brands
          = link_to '#', class: 'brand' do
            = image_tag 'https://gyazo.com/550cb37c43ddbbc1f987c3bfee430380.png',class: ''
            ブランドから探す
          %ul.brands
            %li.brands-list
              = link_to "シャネル", brand_path(id: 125), class: "brands-list--name"
            %li.brands-list
              = link_to "ナイキ", brand_path(id: 128), class: "brands-list--name"
            %li.brands-list
              = link_to "ルイ ヴィトン", brand_path(id: 126), class: "brands-list--name"
            %li.brands-list
              = link_to "シュプリーム", brand_path(id: 127), class: "brands-list--name"
            %li.brands-list
              = link_to "アディダス", brand_path(id: 42), class: "brands-list--name"
            %li.brands-list
              = link_to "ブランド一覧", "#", class: "brands-list--name"
      - if user_signed_in?
        %ul.header-inner__bottom__info
          %li.header-inner__bottom__info--like
            = link_to '#', class: 'like' do
              %i.far.fa-heart.fa-lg.like--icon
              いいね！一覧
          %li.header-inner__bottom__info--notice
            = link_to "#", class: 'notice' do
              %i.far.fa-bell.fa-lg.notice--icon
              お知らせ
          %li.header-inner__bottom__info--todo
            = link_to '#', class: 'todo' do
              %i.fas.fa-check.fa-lg.todo--icon
              やることリスト
            = image_tag '/images/todo_image.png', class:"header-inner__bottom__info--todo--box"
          %li.header-inner__bottom__info--mypage
            = link_to users_path, class: 'mypage' do
              = image_tag 'mypage.png', class: 'mypage--icon'
              マイページ
            .mypage-contents
              = image_tag 'mypage.png', class: 'mypage-contents--icon'
              .mypage-contents__bgimage
              .mypage-contents__main
                .mypage-contents__main--name  
                  = current_user.nickname
                .mypage-contents__main--info.clearfix
                  .mypage-contents__main--info--evaluation
                    評価：０
                  .mypage-contents__main--info--exhibit
                    = "出品数：#{current_user.products.length}"
                .mypage-contents__main--sales.clearfix
                  .mypage-contents__main--sales--text
                    売上金
                  .mypage-contents__main--sales--value
                    ¥0
                  %i.fas.fa-chevron-right.mypage-contents__main--sales--icon
                .mypage-contents__main--point.clearfix
                  .mypage-contents__main--point--text
                    ポイント
                  .mypage-contents__main--point--value
                    P0
                  %i.fas.fa-chevron-right.mypage-contents__main--sales--icon
              .mypage-contents__form
                = link_to "いいね！一覧", "#", class: "mypage-form--content"
                %i.fas.fa-chevron-right.mypage-contents__form--icon
              .mypage-contents__form
                = link_to "出品した商品 - 出品中", exhibit_list_user_path(id: current_user.id), class: "mypage-form--content"
                %i.fas.fa-chevron-right.mypage-contents__form--icon
              .mypage-contents__form
                = link_to "出品した商品 - 取引中", "#", class: "mypage-form--content"
                %i.fas.fa-chevron-right.mypage-contents__form--icon
              .mypage-contents__form
                = link_to "出品した商品 - 売却済み", "#", class: "mypage-form--content"
                %i.fas.fa-chevron-right.mypage-contents__form--icon
      - else  
        %ul.header-inner__bottom__info
          %li.header-inner__bottom__info--signup
            = link_to '新規会員登録', new_user_registration_path, class: 'header-inner__bottom__info--signup--btn'
          %li.header-inner__bottom__info--signin
            = link_to 'ログイン', new_user_session_path, class: 'header-inner__bottom__info--signin--btn'

app/views/products/buy.html.haml
%html#mypage-all
  %body#mypage-show
    %header.products__header--buy
      = link_to image_tag('Mercari_logo.svg', height: '49px', width: '185px'), '/'
    %main.products__content--buy
      %section.products__content--buy--container
        %header.products__content--buy--container--header
          %h2.products__content--buy--container--header--title
            購入内容の確認
        .products__content--buy--item
          = image_tag @product.images[0].picture.to_s, alt: 'picture', height: '64px', width: '64px', class: 'products__content--buy--item--photo'
          %tt.products__content--buy--item--text 
            = @product.name
        .products__content--buy--form
          .products__content--buy--price
            .products__content--buy--price--text
              .products__content--buy--price--text--main 
                = "¥#{@product.price.to_s(:delimited, delimiter: ',')}"
              .products__content--buy--price--text--addition
                送料込み
          .products__content--buy--point
            %p.products__content--buy--point--text
              ポイントはありません
          .products__content--buy--pay
            %span.products__content--buy--pay--left 支払い金額
            .products__content--buy--pay--right 
              = "¥#{@product.price.to_s(:delimited, delimiter: ',')}"
          - if @card_information.present?
            = form_tag(pay_product_path, method: :post) do
              %button.products__content--buy--select 購入する
          - else
            .products__content--buy--no-select 購入する
        = render 'shared/user_information'
      %footer.products__content--buy--footer
        = link_to '#', class: 'products__content--buy--footer--link' do
          %tt プライバシーポリシー
        = link_to '#', class: 'products__content--buy--footer--link' do
          %tt メルカリ利用規約
        = link_to '#', class: 'products__content--buy--footer--link' do
          %tt 特定商品に関する表記
        .products__content--buy--footer--img
          = link_to image_tag('mercari-footer-logo.png', height: '70px', width: '80px', class: 'products__content--buy--footer--img--photo'), '/'
          %p.products__content--buy--footer--img--text
            © 2019 Mercari

app/views/products/create.html.haml
%h1 商品を出品しました！！

app/views/products/product_show.html.haml
= render partial: 'header_index', locals: {parents: @parents}
.exhibit
  .item.margin-left-37.width-775
    %h1.item__name
      = @product.name
    %p.item__wording.p-item-detail
    .item__main-content.clearfix-item-detail
      .item__main-content__photo.width-335
        .item__main-content__photo__detail
          %ul.item__main-content__photo__detail__stage
            - @images.each.with_index do |p,i|
              %li.item__main-content__photo__detail__stage__item
                = image_tag p.picture.url, class:'item__main-content__photo__detail__stage__item__image'
        %ul.item__main-content__photo__details
          - @images.each.with_index do |p,i|
            %li.item__main-content__photo__details__dot
              = image_tag p.picture.url, class:'item__main-content__photo__details__dot__image'  
      %table.item__main-content__detail-table.width-335.height-465
        %tr.item__main-content__detail-table__row
          %th.item__main-content__detail-table__row__header 出品者
          %td.item__main-content__detail-table__row__data
            %div
              = @product.user.nickname
        %tr.item__main-content__detail-table__row
          %th.item__main-content__detail-table__row__header カテゴリー
          %td.item__main-content__detail-table__row__data
            .link-item-detail
              = link_to "#{@category.parent.parent.name}",category_path(@category.parent.parent.id),class:"link-blue-color" 
            .link-item-detail
              %i.fa.fa-chevron-right.icon-item-detail
              = link_to "#{@category.parent.name}",category_path(@category.parent.id),class:"link-blue-color" 
            .link-item-detail
              %i.fa.fa-chevron-right.icon-item-detail
              = link_to "#{@category.name}",category_path(@category.id),class:"link-blue-color" 
        %tr.item__main-content__detail-table__row
          %th.item__main-content__detail-table__row__header ブランド
          %td.item__main-content__detail-table__row__data
            - if @product.brand.present?
              = link_to "#{@product.brand.name}", brand_path(@product.brand_id),class:"link-blue-color"
        %tr.item__main-content__detail-table__row
          %th.item__main-content__detail-table__row__header 商品の状態
          %td.item__main-content__detail-table__row__data
            = @product.status
        %tr.item__main-content__detail-table__row
          %th.item__main-content__detail-table__row__header 配送料の負担
          %td.item__main-content__detail-table__row__data
            = @product.d_charge
        %tr.item__main-content__detail-table__row
          %th.item__main-content__detail-table__row__header 配送の方法
          %td.item__main-content__detail-table__row__data
            = @product.d_method
        %tr.item__main-content__detail-table__row
          %th.item__main-content__detail-table__row__header 配送元地域
          %td.item__main-content__detail-table__row__data
            .link-item-detail.link-blue-color
              = @product.d_origin
        %tr.item__main-content__detail-table__row
          %th.item__main-content__detail-table__row__header 発送日の目安
          %td.item__main-content__detail-table__row__data
            = @product.d_interval
    .item__price-box
      %span.item__price-box__price
        = "￥#{@product.price.to_s(:delimited, delimiter:',')}" 
      %span.item__price-box__tax (税込)
      %span.item__price-box__shipping-fee 送料込み
    .item__description
      %p.item__description-inner.p-item-detail
        = @product.introduction
  .information
    = link_to '商品編集',  edit_product_path(@product) ,data: {"turbolinks" => false}, class:"information__edit"
    %p.or or
    .information__stop  出品を一旦停止する
    .information__delete#dlt_btn この商品を削除する
  .comment-area
    .comment-area__message
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    %textarea.textarea-default{name:"", type: "text", value: "", class: "comment-area__form"}
    .comment-area__send コメントする
= render partial: 'shared/footer'
.gray_panel#gray_panel
.popup{style:"display: none;"}
  .popup__message
    %p.confirmation
      確認
    %p.text1
      削除すると二度と復活できません。
      %br
      削除する代わりに停止することもできます。
    %p.text2
      本当に削除しますか？
  .popup__btn
    .popup__btn--cancel キャンセル
    .popup__btn--delete
      = link_to '削除する', product_path, method: :delete, class: "delete-alert"

app/views/products/show.html.haml
%html
  %body#item-detail
    %header
      = render partial: 'header_index', locals: {parents:  @parents}
    %section.item
      %h1.item__name 
        = @product.name
      %p.item__wording.p-item-detail
      .item__main-content.clearfix-item-detail
        .item__main-content__photo
          .item__main-content__photo__frame
            .item__main-content__photo__frame__stage-outer
              %ul.item__main-content__photo__frame__stage-outer__stage
                - @product.images.each.with_index do |p,i|
                  %li.item__main-content__photo__frame__stage-outer__stage__item                   
                    = image_tag p.picture.url, class: "item__main-content__photo__frame__stage-outer__stage__item__image"                                
          %ul.item__main-content__photo__frame__dots
            - @product.images.each.with_index do |p,i|
              %li.item__main-content__photo__frame__dots__dot 
                = image_tag p.picture.url,class: "item__main-content__photo__frame__dots__dot__image"
        %table.item__main-content__detail-table
          %tr.item__main-content__detail-table__row
            %th.item__main-content__detail-table__row__header 出品者
            %td.item__main-content__detail-table__row__data
              %div
                = link_to "#{@product.user.nickname}","/users", class: "item__main-content__detail-table__row__data__user link-item-detail link-blue-color"
              %div.item__main-content__detail-table__row__data__rate
                .item__main-content__detail-table__row__data__rate__user-ratings 
                  %i.fa.fa-grin.icon-item-detail
                  %span
                  = @product.user.v_good
                .item__main-content__detail-table__row__data__rate__user-ratings
                  %i.fa.fa-meh.icon-item-detail
                  %span 
                  = @product.user.v_accept
                .item__main-content__detail-table__row__data__rate__user-ratings
                  %i.fa.fa-frown.icon-item-detail
                  %span
                  = @product.user.v_bad
          %tr.item__main-content__detail-table__row
            %th.item__main-content__detail-table__row__header カテゴリー
            %td.item__main-content__detail-table__row__data
              %div
                = link_to "#{@parent_category_name}", category_path(@parent_category_id), class: "link-item-detail link-blue-color"
              %div
                %i.fa.fa-chevron-right.icon-item-detail
                = link_to "#{@child_category_name}",category_path(@child_category_id), class: "link-item-detail link-blue-color"
              %div
                %i.fa.fa-chevron-right.icon-item-detail
                = link_to "#{@product.category.name}", category_path(@product.category_id), class: "link-item-detail link-blue-color"
          %tr.item__main-content__detail-table__row
            %th.item__main-content__detail-table__row__header ブランド
            %td.item__main-content__detail-table__row__data
              - if @product.brand_id.present?
                = link_to "#{@product.brand.name}", brand_path(@product.brand_id),class:'link-item-detail link-blue-color'
          %tr.item__main-content__detail-table__row
            %th.item__main-content__detail-table__row__header 商品の状態
            %td.item__main-content__detail-table__row__data
              = @product.status
          %tr.item__main-content__detail-table__row
            %th.item__main-content__detail-table__row__header 配送料の負担
            %td.item__main-content__detail-table__row__data
              = @product.d_charge
          %tr.item__main-content__detail-table__row
            %th.item__main-content__detail-table__row__header 配送の方法
            %td.item__main-content__detail-table__row__data 
              = @product.d_method
          %tr.item__main-content__detail-table__row
            %th.item__main-content__detail-table__row__header 配送元地域
            %td.item__main-content__detail-table__row__data
              %div
                = link_to "#{@product.d_origin}",'#', class: "link-item-detail link-blue-color"
          %tr.item__main-content__detail-table__row
            %th.item__main-content__detail-table__row__header 発送日の目安
            %td.item__main-content__detail-table__row__data
              = @product.d_interval
      .item__price-box
        %span.item__price-box__price
          = "￥#{@product.price.to_s(:delimited, delimiter:',')}"
        %span.item__price-box__tax (税込)
        %span.item__price-box__shipping-fee
          = @product.d_charge.sub!(/\(.*/, "")
      %div
        = link_to '購入画面に進む', buy_product_path(@product.id), class: "item__buy-btn link-item-detail"
      %p.item__shipping-not-allowed-message
        = @product.d_method == 'ゆうゆうメルカリ便' ? "この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。" : ""
      .item__description
        %p.item__description-inner.p-item-detail
          = @product.introduction 
      .item__button-container.clearfix-item-detail
        .item__button-container__button-left
          .item__button-container__button-left__button-like.link-item-detail
            %i.fa.fa-heart.icon-item-detail
            %span.item__button-container__button-left__button-like__letter いいね!
            %span.item__button-container__button-left__button-like__letter 3
            = link_to "", root_path
          .item__button-container__button-left__button-report.link-item-detail.clearfix-item-detail
            %i.fa.fa-flag.icon-item-detail
            %span.item__button-container__button-left__button-report__letter 不適切な商品の報告
            = link_to "", root_path
        .item__button-container__button-right
          .item__button-container__button-right__link-safety.link-item-detail
            %i.fa.fa-lock.icon-item-detail
            %span.item__button-container__button-right__link-safety__letter あんしん・あんぜんへの取り組み
            = link_to "", root_path
    .item-detail-message
    %ul.item-link.clearfix-item-detail
      %li.item-link__prev
        %div.item-link__prev__blue-link
          %i.fa.fa-chevron-left
          =link_to "#{@previous_product.name}", product_path(@previous_product.id), class: "link-item-detail link-current-color"
      %li.item-link__next
        %div.item-link__next__blue-link 
          =link_to "#{@next_product.name}", product_path(@next_product.id), class: "link-item-detail link-current-color"
          %i.fa.fa-chevron-right
    .social-media-content
      .social-media-content__text
      %ul.social-media-content__box
        %li.social-media-content__box__list
          %a.social-media-content__box__list__share-btn.link-item-detail
            %i.fab.fa-facebook-square.icon-item-detail
        %li.social-media-content__box__list
          %a.social-media-content__box__list__share-btn.link-item-detail
            %i.fab.fa-twitter-square.icon-item-detail
        %li.social-media-content__box__list
          %a.social-media-content__box__list__share-btn
            %i.fab.fa-line.icon-item-detail
        %li.social-media-content__box__list
          %a.social-media-content__box__list__share-btn.link-item-detail
            %i.fab.fa-pinterest-square.icon-item-detail
    .items-in-user-profile
      %section.items-in-user-profile__container.clearfix-item-detail
        %h2.items-in-user-profile__container__head
          = link_to "#{@product.user.nickname}さんのその他の出品", "/users", class: "items-in-user-profile__container__head__link link-item-detail link-blue-color"
        .items-in-user-profile__container__content.clearfix-item-detail
          - @ordered_other_products.each do|product|
            %section.items-in-user-profile__container__content__block                 
              = link_to product_path(product.id), class:'items-in-user-profile__container__content__block__link link-item-detail' do
                %figure.items-in-user-profile__container__content__block__link__photo   
                  = image_tag product.images[0].picture.url,class:'items-in-user-profile__container__content__block__link__photo__image'
                .items-in-user-profile__container__content__block__link__body
                  %h3.items-in-user-profile__container__content__block__link__body__name 
                    = product.name
                  .items-in-user-profile__container__content__block__link__body__num
                    .items-in-user-profile__container__content__block__link__body__num__price
                      = "￥#{product.price.to_s(:delimited, delimiter:',')}"
                    .items-in-user-profile__container__content__block__link__body__num__mark
                      %i.fa.fa-heart.icon-item-detail
                      %span.items-in-user-profile__container__content__block__link__body__num__mark__lank
                        = product.likes_count
      %section.items-in-user-profile__container.clearfix-item-detail
        %h2.items-in-user-profile__container__head
          =link_to "#{@product.category.name} その他の商品",category_path(@product.category_id),class: "items-in-user-profile__container__head__link link-item-detail link-blue-color"
        .items-in-user-profile__container__content.clearfix-item-detail
          - @same_category_products.each do|product|
            %section.items-in-user-profile__container__content__block
              = link_to product_path(product.id),class:'items-in-user-profile__container__content__block__link link-item-detail' do
                %figure.items-in-user-profile__container__content__block__link__photo   
                  = image_tag product.images[0].picture.url,class:'items-in-user-profile__container__content__block__link__photo__image'
                .items-in-user-profile__container__content__block__link__body
                  %h3.items-in-user-profile__container__content__block__link__body__name 
                    = product.name
                  .items-in-user-profile__container__content__block__link__body__num
                    .items-in-user-profile__container__content__block__link__body__num__price
                      = "￥#{product.price.to_s(:delimited, delimiter:',')}"
                    .items-in-user-profile__container__content__block__link__body__num__mark
                      %i.fa.fa-heart.icon-item-detail
                      %span.items-in-user-profile__container__content__block__link__body__num__mark__lank
                        = product.likes_count
    %nav.pos-bottom
      %ul.pos-bottom__list
        %li.pos-bottom__list__left-part
          %span
            =link_to "メルカリ", root_path, class: "link-item-detail link-current-color"
          %i.fa.fa-chevron-right.icon-item-detail
        %li.pos-bottom__list__right-part
          %span
            = "#{@product.name}" 
    %footer
      = render partial: "shared/footer"